version: '2'
services:
    app:
        image: money_manager_app
        restart: on-failure
        expose:
            - 5000
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            DB_URI: "postgresql://money-saver:secret_pwd@postgres:5432/money_manager"
    postgres:
        image: money_manager_postgres
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: secret_pwd
            POSTGRES_USER: money-saver
            POSTGRES_DB: money_manager

