version: '2.0'

services:
    app:
        build: .
        ports:
            - 5000:5000
        environment:
            FLASK_DEBUG: 0
            FLASK_APP: init.py
            USE_RELOAD: 'False'
            USE_DEBUGGER: 'False'
        command:
            - "gunicorn"
            - "-c"
            - "/app/config/app/config.py"
            - "init:application"
        volumes:
            - .:/app
    postgres:
        build: ./config/postgres/
        ports:
            - 5432:5432
        volumes:
            - ~/Appdata/money/:/var/lib/postgresql/data

