version: '2.0'

services:
    app:
        build: .
        environment:
            FLASK_DEBUG: 1
            FLASK_APP: init.py
        volumes:
            - .:/app
    postgres:
        build: ./config/postgres/
        volumes:
            - ~/Appdata/money/:/var/lib/postgresql/data

